name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Triggers the run whenever you push to main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: .        # The folder where your HTML/frontend files live.
